# Configuration

discord:
  token: ""
  prefix: "</"
  
  guild: ""
  channels:
    welcomeChannel: ""
    leaveChannel: ""
    guideChannel: ""
    membersCounter: ""
    mainInformation: ""
    verifChannel: ""
  
  rolesId:
    kompetegramers: ""
    batch1: ""
    batch2: ""
    batch3: ""
    studyGroup: ""
    researchGroup: ""

database:
  auth: ""

developers:
  - ""
  - ""