# Configuration

discord:
  token: "" # Token Here
  prefix: ""
  
  guild: ""
  channels:
    welcomeChannel: ""
    leaveChannel: ""
    guideChannel: ""
    membersCounter: ""
    verifChannel: ""

database:
  auth: ""

developers:
  - "282363030501720076"
  - "688694650760069158"